name: Run Tests with Docker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Сборка Docker образа с кэшированием
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: docker build -t test-playwright .

      # 3. Запуск тестов
      - name: Run tests
        run: |
          docker run --rm \
            -v $(pwd)/allureres:/app/allureres \
            test-playwright \
            pytest -s -v ./tests --alluredir=./allureres --browser=chromium --browser=firefox --browser=webkit

      # 4. Сохранение артефактов (исправленная версия)
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allureres/
          retention-days: 7

      # 5. Проверка результатов
      - name: Check test results
        if: ${{ failure() }}
        run: |
          echo "::error::Tests failed. Push to main branch rejected."
          exit 1
