name: Run Tests with Docker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Сборка и тегирование образа
      - name: Build and tag Docker image
        run: |
          docker build -t test-playwright .
          docker tag test-playwright test-playwright:latest

      # 3. Проверка что образ создан
      - name: Verify Docker image
        run: docker images

      # 4. Запуск тестов с явным указанием использовать локальный образ
      - name: Run tests
        run: |
          docker run --rm \
            --name test-container \
            -v $(pwd)/allureres:/app/allureres \
            test-playwright:latest \
            pytest -s -v ./tests --alluredir=./allureres --browser=chromium --browser=firefox --browser=webkit

      # 5. Сохранение отчетов
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allureres/
          retention-days: 7
