name: Run Tests with Docker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Сборка Docker образа
      - name: Build Docker image
        run: docker build -t test-playwright .

      # 3. Запуск тестов в Docker контейнере
      - name: Run tests in Docker container
        run: |
          docker run --rm \
            -v $(pwd)/allureres:/app/allureres \
            -p 8080:8080 \
            test-playwright \
            pytest -s -v ./tests --alluredir=./allureres --browser=chromium --browser=firefox --browser=webkit

      # 4. Проверка результатов тестов
      - name: Check test results
        id: check-tests
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed."
            exit 1
          else
            echo "Tests passed successfully."
          fi

      # 5. Отмена пуша при неудачных тестах
      - name: Fail if tests fail
        if: failure()
        run: |
          echo "Tests failed. Push to main branch is canceled."
          exit 1
