name: Run Tests with Docker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Настройка Docker Buildx (вместо кэширования /var/lib/docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Сборка Docker образа с кэшированием через Buildx
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: test-playwright:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 4. Запуск тестов
      - name: Run tests
        run: |
          docker run --rm \
            -v $(pwd)/allureres:/app/allureres \
            test-playwright \
            pytest -s -v ./tests --alluredir=./allureres --browser=chromium --browser=firefox --browser=webkit

      # 5. Сохранение артефактов
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allureres/
          retention-days: 7

      # 6. Проверка результатов
      - name: Check test results
        if: ${{ failure() }}
        run: |
          echo "::error::Tests failed. Push to main branch rejected."
          exit 1
